export type PublicJob = {
  slug: string;
  company: string;
  title: string;
  logo: string;
  location: string;
  salary: string;
  createdAt: string;
  jobType: "Full-Time" | "Part-Time" | "Freelance" | "Internship";
  experience: string;
  workMode: "Onsite" | "Remote" | "Hybrid";
  language: string;
  education: string;
  description: string;
  responsibilities: string[];
  requirements: string[];
  tags: string[];
};

export const publicJobs: PublicJob[] = [
  {
    slug: "product-designer-kaspi",
    company: "Kaspi.kz",
    title: "Graphic Designer",
    logo: "/photo/logo-company/kaspi.jpg",
    location: "Astana, Kazakhstan",
    salary: "600$ / Month",
    createdAt: "3 days ago",
    jobType: "Full-Time",
    experience: "Mid-level",
    workMode: "Remote",
    language: "Kazakh, Russian, English",
    education: "Bachelor degree",
    description:
      "A Graphic Designer creates modern visual materials for digital campaigns, social media, presentations, and brand communication.",
    responsibilities: [
      "Create social media visuals, banners, and promotional graphics.",
      "Design presentation materials and digital layouts.",
      "Work with typography, colors, composition, and brand guidelines.",
      "Prepare visual concepts for advertising campaigns.",
      "Adapt designs for different digital formats.",
      "Collaborate with marketing and product teams.",
    ],
    requirements: [
      "Experience with graphic design tools.",
      "Good understanding of typography, colors, and composition.",
      "Ability to follow brand guidelines.",
      "Portfolio with digital or social media design works.",
    ],
    tags: ["Graphic Design", "Branding", "Social Media"],
  },
  {
    slug: "3d-animator-qazaq-animation",
    company: "Qazaq Animation Studio",
    title: "3D Animator",
    logo: "/photo/logo-company/QazaqAnimation.jpg",
    location: "Shymkent, Kazakhstan",
    salary: "600 000₸ / Month",
    createdAt: "4 days ago",
    jobType: "Full-Time",
    experience: "High-level",
    workMode: "Remote",
    language: "Russian, English",
    education: "Bachelor degree",
    description:
      "A 3D Animator creates animated characters, product videos, and 3D scenes for digital media, advertising, and entertainment projects.",
    responsibilities: [
      "Create 3D character animation and movement cycles.",
      "Work with rigged characters, objects, and 3D scenes.",
      "Prepare animated product videos and short promotional clips.",
      "Set up lighting, camera angles, and rendering scenes.",
      "Collaborate with modelers, designers, and directors.",
      "Improve animation timing, movement, and visual rhythm.",
    ],
    requirements: [
      "Experience in 3D animation.",
      "Understanding of character animation and rendering.",
      "Ability to work with creative teams.",
      "Portfolio with 3D animation projects.",
    ],
    tags: ["3D Animation", "Character Animation", "Rendering"],
  },
  {
    slug: "marketing-specialist-choco-group",
    company: "Choco Group",
    title: "Marketing Specialist",
    logo: "/photo/logo-company/ChocoGroup.jpg",
    location: "Almaty, Kazakhstan",
    salary: "100 000₽ / Month",
    createdAt: "6 days ago",
    jobType: "Full-Time",
    experience: "Mid-level",
    workMode: "Hybrid",
    language: "Russian, English",
    education: "Bachelor degree",
    description:
      "A Marketing Specialist develops campaigns, content strategies, and promotional ideas to increase brand awareness and audience engagement.",
    responsibilities: [
      "Develop marketing campaigns for digital platforms.",
      "Prepare content plans and promotional ideas.",
      "Analyze target audience and competitor activity.",
      "Work with social media content and advertising materials.",
      "Coordinate campaigns with designers and copywriters.",
      "Track campaign results and prepare reports.",
    ],
    requirements: [
      "Experience in digital marketing or SMM.",
      "Understanding of campaign planning.",
      "Ability to analyze audience and competitors.",
      "Good communication and reporting skills.",
    ],
    tags: ["Marketing", "SMM", "Campaign Planning"],
  },
  {
    slug: "screenwriter-steppe-film-production",
    company: "Steppe Film Production",
    title: "Screenwriter",
    logo: "/photo/logo-company/SteppeFilm.jpg",
    location: "Astana, Kazakhstan",
    salary: "300 000₸ / Month",
    createdAt: "3 days ago",
    jobType: "Part-Time",
    experience: "Junior",
    workMode: "Remote",
    language: "Kazakh, Russian",
    education: "Not required",
    description:
      "A Screenwriter creates scripts, dialogues, story concepts, and narrative structures for films, commercials, social media videos, and digital content.",
    responsibilities: [
      "Write scripts for short films, ads, and online videos.",
      "Develop story ideas, characters, and scene structure.",
      "Create dialogues and narration texts.",
      "Adapt scripts for social media and commercial formats.",
      "Work with directors, producers, and creative teams.",
      "Edit and improve scripts based on feedback.",
    ],
    requirements: [
      "Strong storytelling skills.",
      "Ability to write clear dialogues and scripts.",
      "Understanding of video and social media formats.",
      "Portfolio or examples of written scripts.",
    ],
    tags: ["Screenwriting", "Script", "Film"],
  },
  {
    slug: "photographer-cinematographer-luna-fashion",
    company: "Luna Fashion Store",
    title: "Photographer / Cinematographer",
    logo: "/photo/logo-company/LunaFashion.png",
    location: "Shymkent, Kazakhstan",
    salary: "300 000₸ / Month",
    createdAt: "4 days ago",
    jobType: "Full-Time",
    experience: "Junior",
    workMode: "Onsite",
    language: "Russian, English",
    education: "Not required",
    description:
      "A Photographer / Cinematographer creates fashion photos, product visuals, lifestyle shots, and cinematic content for brand promotion.",
    responsibilities: [
      "Shoot fashion lookbooks, portraits, and product photos.",
      "Create lifestyle visuals for social media and website use.",
      "Work with models, stylists, and creative directors.",
      "Set up lighting and composition for indoor and outdoor shoots.",
      "Edit and retouch photo materials.",
      "Support video shooting for fashion campaigns.",
    ],
    requirements: [
      "Strong photography or cinematography portfolio.",
      "Understanding of lighting, color, and composition.",
      "Experience with fashion or product shoots.",
      "Basic editing and retouching skills.",
    ],
    tags: ["Photography", "Cinematography", "Fashion"],
  },
  {
    slug: "videographer-soprano-karaoke",
    company: "Soprano Karaoke",
    title: "Videographer",
    logo: "/photo/logo-company/Soprano.png",
    location: "Astana, Kazakhstan",
    salary: "700$ / Month",
    createdAt: "2 days ago",
    jobType: "Full-Time",
    experience: "Senior",
    workMode: "Onsite",
    language: "Kazakh, Russian",
    education: "Not required",
    description:
      "A Videographer films promotional videos, event content, interviews, and short social media videos with strong composition and cinematic style.",
    responsibilities: [
      "Film event videos, reels, and promotional content.",
      "Work with camera angles, lighting, and composition.",
      "Capture atmosphere, guests, details, and brand elements.",
      "Prepare video materials for editing and publication.",
      "Collaborate with marketing and content teams.",
      "Support creative ideas for video campaigns.",
    ],
    requirements: [
      "Experience with camera work.",
      "Good understanding of lighting and composition.",
      "Ability to film events and promotional content.",
      "Portfolio with video projects.",
    ],
    tags: ["Videography", "Camera Work", "Event Video"],
  },
  {
    slug: "producer-nomad-film-group",
    company: "Nomad Film Group",
    title: "Producer",
    logo: "/photo/logo-company/NomadFilm.jpg",
    location: "Almaty, Kazakhstan",
    salary: "750$ / Month",
    createdAt: "4 days ago",
    jobType: "Full-Time",
    experience: "Senior",
    workMode: "Onsite",
    language: "Kazakh, Russian",
    education: "Bachelor degree",
    description:
      "A Producer manages creative media projects, production schedules, budgets, teams, locations, and communication between clients and specialists.",
    responsibilities: [
      "Plan and organize video and media production projects.",
      "Manage schedules, budgets, teams, and locations.",
      "Communicate with clients, directors, and creative specialists.",
      "Coordinate casting, equipment, and shooting preparation.",
      "Control deadlines and production documents.",
      "Support the project from pre-production to final delivery.",
    ],
    requirements: [
      "Experience in production management.",
      "Ability to manage budgets, schedules, and teams.",
      "Strong communication and organization skills.",
      "Understanding of film or media production process.",
    ],
    tags: ["Production", "Project Management", "Film"],
  },
  {
    slug: "video-editor-digital-media-astana",
    company: "Digital Media Astana",
    title: "Video Editor",
    logo: "/photo/logo-company/DigitalMedia.jpg",
    location: "Astana, Kazakhstan",
    salary: "650$ / Month",
    createdAt: "3 days ago",
    jobType: "Full-Time",
    experience: "Mid-level",
    workMode: "Remote",
    language: "Russian, English",
    education: "Not required",
    description:
      "A Video Editor creates clean and dynamic video edits for social media, events, interviews, YouTube, advertising, and brand content.",
    responsibilities: [
      "Edit videos for Instagram, YouTube, TikTok, and presentations.",
      "Select the best moments from raw footage.",
      "Work with music, transitions, subtitles, and sound sync.",
      "Prepare vertical and horizontal video formats.",
      "Add basic color correction and motion elements.",
      "Collaborate with videographers and content managers.",
    ],
    requirements: [
      "Experience with video editing software.",
      "Understanding of pacing, subtitles, and music rhythm.",
      "Ability to work with vertical and horizontal formats.",
      "Portfolio with edited video works.",
    ],
    tags: ["Video Editing", "Post-production", "Reels"],
  },
  {
    slug: "motion-designer-pixel-motion-studio",
    company: "Pixel Motion Studio",
    title: "Motion Designer",
    logo: "/photo/logo-company/PixelMotion.png",
    location: "Almaty, Kazakhstan",
    salary: "750$ / Month",
    createdAt: "6 days ago",
    jobType: "Full-Time",
    experience: "Mid-level",
    workMode: "Remote",
    language: "Russian, English",
    education: "Bachelor degree",
    description:
      "A Motion Designer creates animated graphics, logo animations, typography motion, social media animations, and promotional video elements.",
    responsibilities: [
      "Create motion graphics for ads, social media, and presentations.",
      "Animate logos, typography, icons, and visual elements.",
      "Prepare storyboards and animation concepts.",
      "Work with designers and marketing teams.",
      "Adapt animations for different screen formats.",
      "Export final files for web, social media, and video platforms.",
    ],
    requirements: [
      "Experience with motion design.",
      "Knowledge of After Effects or similar tools.",
      "Understanding of animation timing and visual rhythm.",
      "Portfolio with motion graphics projects.",
    ],
    tags: ["Motion Design", "Animation", "After Effects"],
  },
  {
    slug: "director-almaty-vision-studio",
    company: "Almaty Vision Studio",
    title: "Director",
    logo: "/photo/logo-company/Vision.jpg",
    location: "Almaty, Kazakhstan",
    salary: "800 000₸ / Month",
    createdAt: "5 days ago",
    jobType: "Full-Time",
    experience: "Senior",
    workMode: "Onsite",
    language: "Kazakh, Russian",
    education: "Bachelor degree",
    description:
      "A Director creates visual concepts, directs scenes, works with actors and production teams, and controls the storytelling style of video projects.",
    responsibilities: [
      "Develop creative concepts and visual direction.",
      "Direct scenes, actors, camera movement, and mood.",
      "Work with producers, cinematographers, editors, and clients.",
      "Prepare shot lists, references, and scene plans.",
      "Control storytelling, pacing, and emotional tone.",
      "Present creative ideas to the production team and client.",
    ],
    requirements: [
      "Experience in directing or creative production.",
      "Strong visual storytelling skills.",
      "Ability to work with production teams and clients.",
      "Portfolio with video or film projects.",
    ],
    tags: ["Directing", "Film", "Creative Direction"],
  },
  {
    slug: "graphic-designer-mediapro",
    company: "MediaPro",
    title: "Graphic Designer",
    logo: "https://images.unsplash.com/photo-1613909207039-6b173b755cc1?auto=format&fit=crop&w=300&q=90",
    location: "Astana, Kazakhstan",
    salary: "300$ / Month",
    createdAt: "10 days ago",
    jobType: "Part-Time",
    experience: "Junior",
    workMode: "Remote",
    language: "Kazakh, Russian",
    education: "Not required",
    description:
      "MediaPro needs a part-time Graphic Designer for social layouts, posters, and simple brand materials.",
    responsibilities: [
      "Design social media posts",
      "Create posters and banners",
      "Adapt templates for campaigns",
      "Prepare files for publishing",
    ],
    requirements: [
      "Basic experience in graphic design.",
      "Ability to create social media layouts and posters.",
      "Knowledge of Canva or Figma.",
      "Portfolio with simple visual design works.",
    ],
    tags: ["Graphic Design", "Canva", "Figma"],
  },
  
];

export function getPublicJobBySlug(slug: string) {
  return publicJobs.find((job) => job.slug === slug);
}

export const kazakhstanCities = [
  "All Kazakhstan",
  "Astana, Kazakhstan",
  "Almaty, Kazakhstan",
  "Shymkent, Kazakhstan",
  "Aktobe, Kazakhstan",
  "Karaganda, Kazakhstan",
  "Atyrau, Kazakhstan",
  "Pavlodar, Kazakhstan",
  "Taraz, Kazakhstan",
  "Kokshetau, Kazakhstan",
  "Turkistan, Kazakhstan",
  "Online",
];
